<?php
/**
 * AadIdentifierTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SaaS fulfillment APIs, version 2
 *
 * This spec details the APIs that enable partners to sell their SaaS applications in the AppSource marketplace and the Azure Marketplace. These APIs are a requirement for transactable SaaS offers on the AppSource and Azure Marketplace.
 *
 * OpenAPI spec version: 2018-08-31
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20-SNAPSHOT
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * AadIdentifierTest Class Doc Comment
 *
 * @category    Class
 * @description AadIdentifier
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AadIdentifierTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AadIdentifier"
     */
    public function testAadIdentifier()
    {
    }

    /**
     * Test attribute "email_id"
     */
    public function testPropertyEmailId()
    {
    }

    /**
     * Test attribute "object_id"
     */
    public function testPropertyObjectId()
    {
    }

    /**
     * Test attribute "tenant_id"
     */
    public function testPropertyTenantId()
    {
    }

    /**
     * Test attribute "puid"
     */
    public function testPropertyPuid()
    {
    }
}
