<?php
/**
 * SaasMarketplaceMeterApi
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SaaS fulfillment APIs, version 2
 *
 * This spec details the APIs that enable partners to sell their SaaS applications in the AppSource marketplace and the Azure Marketplace. These APIs are a requirement for transactable SaaS offers on the AppSource and Azure Marketplace.
 *
 * OpenAPI spec version: 2018-08-31
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20-SNAPSHOT
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\azure.marketplace.api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Swagger\Client\ApiException;
use Swagger\Client\Configuration;
use Swagger\Client\HeaderSelector;
use Swagger\Client\ObjectSerializer;

/**
 * SaasMarketplaceMeterApi Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SaasMarketplaceMeterApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation meteringPostBatchUsageEvent
     *
     * Posts a set of usage events to the marketplace metering service API.
     *
     * @param  \Swagger\Client\azure.marketplace\UsageEvent[] $body body (required)
     * @param  \Swagger\Client\azure.marketplace\ApiVersion $api_version Version of the API. (required)
     * @param  string $x_ms_requestid A unique string value for tracking the request from the client, preferably a GUID. If this value isn&#x27;t provided, one will be generated and provided in the response headers. (optional)
     * @param  string $x_ms_correlationid A unique string value for operation on the client. This parameter correlates all events from client operation with events on the server side. If this value isn&#x27;t provided, one will be generated and provided in the response headers. (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\azure.marketplace\UsageEventOkResponse
     */
    public function meteringPostBatchUsageEvent($body, $api_version, $x_ms_requestid = null, $x_ms_correlationid = null)
    {
        list($response) = $this->meteringPostBatchUsageEventWithHttpInfo($body, $api_version, $x_ms_requestid, $x_ms_correlationid);
        return $response;
    }

    /**
     * Operation meteringPostBatchUsageEventWithHttpInfo
     *
     * Posts a set of usage events to the marketplace metering service API.
     *
     * @param  \Swagger\Client\azure.marketplace\UsageEvent[] $body (required)
     * @param  \Swagger\Client\azure.marketplace\ApiVersion $api_version Version of the API. (required)
     * @param  string $x_ms_requestid A unique string value for tracking the request from the client, preferably a GUID. If this value isn&#x27;t provided, one will be generated and provided in the response headers. (optional)
     * @param  string $x_ms_correlationid A unique string value for operation on the client. This parameter correlates all events from client operation with events on the server side. If this value isn&#x27;t provided, one will be generated and provided in the response headers. (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\azure.marketplace\UsageEventOkResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function meteringPostBatchUsageEventWithHttpInfo($body, $api_version, $x_ms_requestid = null, $x_ms_correlationid = null)
    {
        $returnType = '\Swagger\Client\azure.marketplace\UsageEventOkResponse';
        $request = $this->meteringPostBatchUsageEventRequest($body, $api_version, $x_ms_requestid, $x_ms_correlationid);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\azure.marketplace\UsageEventOkResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation meteringPostBatchUsageEventAsync
     *
     * Posts a set of usage events to the marketplace metering service API.
     *
     * @param  \Swagger\Client\azure.marketplace\UsageEvent[] $body (required)
     * @param  \Swagger\Client\azure.marketplace\ApiVersion $api_version Version of the API. (required)
     * @param  string $x_ms_requestid A unique string value for tracking the request from the client, preferably a GUID. If this value isn&#x27;t provided, one will be generated and provided in the response headers. (optional)
     * @param  string $x_ms_correlationid A unique string value for operation on the client. This parameter correlates all events from client operation with events on the server side. If this value isn&#x27;t provided, one will be generated and provided in the response headers. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function meteringPostBatchUsageEventAsync($body, $api_version, $x_ms_requestid = null, $x_ms_correlationid = null)
    {
        return $this->meteringPostBatchUsageEventAsyncWithHttpInfo($body, $api_version, $x_ms_requestid, $x_ms_correlationid)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation meteringPostBatchUsageEventAsyncWithHttpInfo
     *
     * Posts a set of usage events to the marketplace metering service API.
     *
     * @param  \Swagger\Client\azure.marketplace\UsageEvent[] $body (required)
     * @param  \Swagger\Client\azure.marketplace\ApiVersion $api_version Version of the API. (required)
     * @param  string $x_ms_requestid A unique string value for tracking the request from the client, preferably a GUID. If this value isn&#x27;t provided, one will be generated and provided in the response headers. (optional)
     * @param  string $x_ms_correlationid A unique string value for operation on the client. This parameter correlates all events from client operation with events on the server side. If this value isn&#x27;t provided, one will be generated and provided in the response headers. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function meteringPostBatchUsageEventAsyncWithHttpInfo($body, $api_version, $x_ms_requestid = null, $x_ms_correlationid = null)
    {
        $returnType = '\Swagger\Client\azure.marketplace\UsageEventOkResponse';
        $request = $this->meteringPostBatchUsageEventRequest($body, $api_version, $x_ms_requestid, $x_ms_correlationid);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'meteringPostBatchUsageEvent'
     *
     * @param  \Swagger\Client\azure.marketplace\UsageEvent[] $body (required)
     * @param  \Swagger\Client\azure.marketplace\ApiVersion $api_version Version of the API. (required)
     * @param  string $x_ms_requestid A unique string value for tracking the request from the client, preferably a GUID. If this value isn&#x27;t provided, one will be generated and provided in the response headers. (optional)
     * @param  string $x_ms_correlationid A unique string value for operation on the client. This parameter correlates all events from client operation with events on the server side. If this value isn&#x27;t provided, one will be generated and provided in the response headers. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function meteringPostBatchUsageEventRequest($body, $api_version, $x_ms_requestid = null, $x_ms_correlationid = null)
    {
        // verify the required parameter 'body' is set
        if ($body === null || (is_array($body) && count($body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $body when calling meteringPostBatchUsageEvent'
            );
        }
        // verify the required parameter 'api_version' is set
        if ($api_version === null || (is_array($api_version) && count($api_version) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $api_version when calling meteringPostBatchUsageEvent'
            );
        }

        $resourcePath = '/batchUsageEvent';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($api_version !== null) {
            $queryParams['api-version'] = ObjectSerializer::toQueryValue($api_version);
        }
        // header params
        if ($x_ms_requestid !== null) {
            $headerParams['x-ms-requestid'] = ObjectSerializer::toHeaderValue($x_ms_requestid);
        }
        // header params
        if ($x_ms_correlationid !== null) {
            $headerParams['x-ms-correlationid'] = ObjectSerializer::toHeaderValue($x_ms_correlationid);
        }


        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation meteringPostUsageEvent
     *
     * Posts a single usage event to the marketplace metering service API.
     *
     * @param  \Swagger\Client\azure.marketplace\UsageEvent[] $body body (required)
     * @param  \Swagger\Client\azure.marketplace\ApiVersion $api_version Version of the API. (required)
     * @param  string $x_ms_requestid A unique string value for tracking the request from the client, preferably a GUID. If this value isn&#x27;t provided, one will be generated and provided in the response headers. (optional)
     * @param  string $x_ms_correlationid A unique string value for operation on the client. This parameter correlates all events from client operation with events on the server side. If this value isn&#x27;t provided, one will be generated and provided in the response headers. (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\azure.marketplace\UsageEventOkResponse
     */
    public function meteringPostUsageEvent($body, $api_version, $x_ms_requestid = null, $x_ms_correlationid = null)
    {
        list($response) = $this->meteringPostUsageEventWithHttpInfo($body, $api_version, $x_ms_requestid, $x_ms_correlationid);
        return $response;
    }

    /**
     * Operation meteringPostUsageEventWithHttpInfo
     *
     * Posts a single usage event to the marketplace metering service API.
     *
     * @param  \Swagger\Client\azure.marketplace\UsageEvent[] $body (required)
     * @param  \Swagger\Client\azure.marketplace\ApiVersion $api_version Version of the API. (required)
     * @param  string $x_ms_requestid A unique string value for tracking the request from the client, preferably a GUID. If this value isn&#x27;t provided, one will be generated and provided in the response headers. (optional)
     * @param  string $x_ms_correlationid A unique string value for operation on the client. This parameter correlates all events from client operation with events on the server side. If this value isn&#x27;t provided, one will be generated and provided in the response headers. (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\azure.marketplace\UsageEventOkResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function meteringPostUsageEventWithHttpInfo($body, $api_version, $x_ms_requestid = null, $x_ms_correlationid = null)
    {
        $returnType = '\Swagger\Client\azure.marketplace\UsageEventOkResponse';
        $request = $this->meteringPostUsageEventRequest($body, $api_version, $x_ms_requestid, $x_ms_correlationid);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\azure.marketplace\UsageEventOkResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation meteringPostUsageEventAsync
     *
     * Posts a single usage event to the marketplace metering service API.
     *
     * @param  \Swagger\Client\azure.marketplace\UsageEvent[] $body (required)
     * @param  \Swagger\Client\azure.marketplace\ApiVersion $api_version Version of the API. (required)
     * @param  string $x_ms_requestid A unique string value for tracking the request from the client, preferably a GUID. If this value isn&#x27;t provided, one will be generated and provided in the response headers. (optional)
     * @param  string $x_ms_correlationid A unique string value for operation on the client. This parameter correlates all events from client operation with events on the server side. If this value isn&#x27;t provided, one will be generated and provided in the response headers. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function meteringPostUsageEventAsync($body, $api_version, $x_ms_requestid = null, $x_ms_correlationid = null)
    {
        return $this->meteringPostUsageEventAsyncWithHttpInfo($body, $api_version, $x_ms_requestid, $x_ms_correlationid)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation meteringPostUsageEventAsyncWithHttpInfo
     *
     * Posts a single usage event to the marketplace metering service API.
     *
     * @param  \Swagger\Client\azure.marketplace\UsageEvent[] $body (required)
     * @param  \Swagger\Client\azure.marketplace\ApiVersion $api_version Version of the API. (required)
     * @param  string $x_ms_requestid A unique string value for tracking the request from the client, preferably a GUID. If this value isn&#x27;t provided, one will be generated and provided in the response headers. (optional)
     * @param  string $x_ms_correlationid A unique string value for operation on the client. This parameter correlates all events from client operation with events on the server side. If this value isn&#x27;t provided, one will be generated and provided in the response headers. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function meteringPostUsageEventAsyncWithHttpInfo($body, $api_version, $x_ms_requestid = null, $x_ms_correlationid = null)
    {
        $returnType = '\Swagger\Client\azure.marketplace\UsageEventOkResponse';
        $request = $this->meteringPostUsageEventRequest($body, $api_version, $x_ms_requestid, $x_ms_correlationid);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'meteringPostUsageEvent'
     *
     * @param  \Swagger\Client\azure.marketplace\UsageEvent[] $body (required)
     * @param  \Swagger\Client\azure.marketplace\ApiVersion $api_version Version of the API. (required)
     * @param  string $x_ms_requestid A unique string value for tracking the request from the client, preferably a GUID. If this value isn&#x27;t provided, one will be generated and provided in the response headers. (optional)
     * @param  string $x_ms_correlationid A unique string value for operation on the client. This parameter correlates all events from client operation with events on the server side. If this value isn&#x27;t provided, one will be generated and provided in the response headers. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function meteringPostUsageEventRequest($body, $api_version, $x_ms_requestid = null, $x_ms_correlationid = null)
    {
        // verify the required parameter 'body' is set
        if ($body === null || (is_array($body) && count($body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $body when calling meteringPostUsageEvent'
            );
        }
        // verify the required parameter 'api_version' is set
        if ($api_version === null || (is_array($api_version) && count($api_version) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $api_version when calling meteringPostUsageEvent'
            );
        }

        $resourcePath = '/usageEvent';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($api_version !== null) {
            $queryParams['api-version'] = ObjectSerializer::toQueryValue($api_version);
        }
        // header params
        if ($x_ms_requestid !== null) {
            $headerParams['x-ms-requestid'] = ObjectSerializer::toHeaderValue($x_ms_requestid);
        }
        // header params
        if ($x_ms_correlationid !== null) {
            $headerParams['x-ms-correlationid'] = ObjectSerializer::toHeaderValue($x_ms_correlationid);
        }


        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
