<?php
/**
 * FulfillmentApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SaaS fulfillment APIs, version 2
 *
 * This spec details the APIs that enable partners to sell their SaaS applications in the AppSource marketplace and the Azure Marketplace. These APIs are a requirement for transactable SaaS offers on the AppSource and Azure Marketplace.
 *
 * OpenAPI spec version: 2018-08-31
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20-SNAPSHOT
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * FulfillmentApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class FulfillmentApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for fulfillmentActivateSubscription
     *
     * Activate a subscription.
     *
     */
    public function testFulfillmentActivateSubscription()
    {
    }

    /**
     * Test case for fulfillmentDeleteSubscription
     *
     * Delete a subscription.
     *
     */
    public function testFulfillmentDeleteSubscription()
    {
    }

    /**
     * Test case for fulfillmentGetSubscription
     *
     * Get subscription.
     *
     */
    public function testFulfillmentGetSubscription()
    {
    }

    /**
     * Test case for fulfillmentListAvailablePlans
     *
     * List available plans.
     *
     */
    public function testFulfillmentListAvailablePlans()
    {
    }

    /**
     * Test case for fulfillmentListSubscriptions
     *
     * List subscriptions.
     *
     */
    public function testFulfillmentListSubscriptions()
    {
    }

    /**
     * Test case for fulfillmentResolve
     *
     * Resolve a subscription.
     *
     */
    public function testFulfillmentResolve()
    {
    }

    /**
     * Test case for fulfillmentUpdateSubscription
     *
     * Patch a subscription.
     *
     */
    public function testFulfillmentUpdateSubscription()
    {
    }
}
